### ISSUE TITLE
Update for changes in remark

### ISSUE THREAD

**Issue by wooorm** [bizen241/remark-inline-math#2]
Hi! 👋

remark just changed: you can read more about the changed [here][1].

That means that this plugin doesn’t work with the latest remark. If you get around to updating, use the previously mentioned changelog for help, but feel free to respond below or ask questions on [Gitter][2]!

[1]: https://github.com/wooorm/remark/releases/tag/7.0.0
[2]: https://gitter.im/wooorm/remark
[3]: https://github.com/wooorm/remark/blob/master/doc/plugins.md#list-of-plugins

**Comment by bizen241** [comment]
Now this plugin works with unified@6.0.0.

I'm sorry for being late.

Thank you for the information.
